# Generated by Django 5.0.2 on 2024-05-02 14:51

import django.db.models.deletion
import eadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coursecode', models.CharField(max_length=15, unique=True)),
                ('coursename', models.CharField(max_length=40)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.examiner')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('examcode', models.CharField(max_length=40, unique=True)),
                ('examname', models.CharField(max_length=40)),
                ('examdate', models.DateField()),
                ('examinerid', models.CharField(default='02', max_length=40)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('paymentref', models.FileField(upload_to=eadmin.models.content_file_name)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicant')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.exam')),
            ],
            options={
                'unique_together': {('reg_no', 'exam')},
            },
        ),
    ]
