# Generated by Django 5.0.2 on 2024-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
